# Generated by Django 5.1.5 on 2025-02-24 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("navigator_info", models.TextField(blank=True, null=True)),
                ("os", models.CharField(blank=True, max_length=255, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VisitInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "location_approx",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("visit_start_datetime", models.DateTimeField(auto_now_add=True)),
                ("visit_end_datetime", models.DateTimeField(blank=True, null=True)),
                ("visit_duration", models.DurationField(blank=True, null=True)),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="visitor_tracker.visitor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="visitor_tra_ip_addr_ee8f50_idx"
                    )
                ],
            },
        ),
    ]
