# Generated by Django 5.1.5 on 2025-04-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id_visitor",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("navigator_info", models.TextField(blank=True, null=True)),
                ("os", models.CharField(blank=True, max_length=255, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VisitInfo",
            fields=[
                (
                    "id_visit_info",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "location_approx",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("visit_start_datetime", models.DateTimeField(auto_now_add=True)),
                ("visit_end_datetime", models.DateTimeField(blank=True, null=True)),
                ("visit_duration", models.DurationField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="visitor_tracker.visitor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="visitor_tra_ip_addr_ee8f50_idx"
                    )
                ],
            },
        ),
    ]
