# Generated by Django 5.1.5 on 2025-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitor_tracker", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.AddField(
            model_name="visitinfo",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
